<?php

/**
 * @file
 * Sometimes it can be hard to track all of the companies that you interview
 * for; the interview_tracker module can help save the day.
 *
 * @author Brian McVeigh
 */

/**
 * Implements hook_menu().
 */
function interview_tracker_menu() {
  $items['interview'] = array(
    'title' => 'Track Interviews',
    'description' => 'Track the status of companies you interviewed with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('interview_tracker_form'),
    'access arguments' => array('view interview tracker'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['interview/%'] = array(
    'title' => 'Track Interview',
    'description' => 'View an interview by id.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('interview_tracker_update_form', 1),
    'access arguments' => array('view interview tracker'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function interview_tracker_permission() {
  return array(
    'view interview tracker' => array(
      'title' => t('View Interview Tracker'),
      'description' => t('View and edit the interview tracker.'),
    ),
  );
}

/**
 * This page contains a table of all the interviews.
 */
function interview_tracker_form($form, &$form_state) {
  $result = interview_tracker_get_interview();

  if (!empty($result)) {
    $rows = array();

    $header = array(
      t('ID'),
      t('Position Applied'),
      t('Company'),
      t('Comment'),
      t('Status'),
      t('Submitted Date'),
    );

    foreach ($result as $row) {
      $rows[] = array(
        $row->id,
        $row->position,
        $row->company,
        $row->comment,
        $row->status_readable,
        date('F j, Y, g:i a', $row->submitted),
      );
    }

    $form['interview_table'] = array(
      '#type' => 'markup',
      '#markup' => theme('table', array('header' => $header, 'rows' => $rows)),
    );
  }

  $form['position'] = array(
    '#type' => 'textfield',
    '#title' => t('Position applied for'),
    '#description' => t('Enter the position you applied for.'),
    '#required' => TRUE,
  );

  $form['company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company Name'),
    '#description' => t('Enter the name of the company you applied to.'),
    '#required' => TRUE,
  );

  $form['comment'] = array(
    '#type' => 'textarea',
    '#title' => t('Enter comments about interview.'),
    '#description' => t('Enter the comments you had about the interview.'),
    '#required' => FALSE,
  );

  $result = interview_tracker_get_status();

  $options = array();

  foreach ($result as $row) {
    $options[$row->id] = $row->status_readable;
  }

  $form['status'] = array(
    '#type' => 'radios',
    '#title' => t('What is the interview status?'),
    '#description' => t('Select the status of the interview.'),
    '#options' => $options,
    '#default_value' => 0,
    '#required' => TRUE,
  );

  $form['procesar'] = array(
    '#type' => 'submit',
    '#value' => t('Add interview!'),
  );

  $form['#submit'][] = 'interview_tracker_form_submit';

  return $form;
}

function interview_tracker_form_submit($form, &$form_state) {
  $dirty_data = $form_state['values'];

  $clean_data = array();

  // Sanitize the data.
  foreach ($dirty_data as $key => $value) {
    $clean_data[$key] = check_plain($value);
  }

  $clean_data['submitted'] = time();

  try {
    $success = drupal_write_record('interview_tracker', $clean_data);

    if ($success) {
      drupal_set_message(t('Success!'));
    }
    else {
      drupal_set_message(t('Error adding interview to database.'), 'error');
    }
  }
  catch (Exception $e) {
    watchdog('error', 'Interview Tracker Error: ' . $e, array(), WATCHDOG_ERROR);
  }
}

/**
 * This is a form that will allow a user to view/edit an interview.
 *
 * @param int $id
 *   The interview id.
 */
function interview_tracker_update_form($form, &$form_state, $id) {
  // Sanitize the id just so it is not vulnerable to XSS attacks.
  $clean_id = filter_xss($id);

  // This should be an array of one result object coming from the database.
  $interview = interview_tracker_get_interview($clean_id)[0];

  $form['position'] = array(
    '#type' => 'textfield',
    '#title' => t('Position'),
    '#default_value' => $interview->position,
  );

  $form['company'] = array(
    '#type' => 'textfield',
    '#title' => t('Company'),
    '#default_value' => $interview->company,
  );

  $form['comment'] = array(
    '#type' => 'textarea',
    '#title' => t('Comment'),
    '#default_value' => $interview->comment,
  );

  // TODO: I know this may look repetitive; I want to get the functionality
  // down first and then I will fix it later. Maybe I'll put this into a
  // function so that it is reusable.
  $result = interview_tracker_get_status();

  $options = array();

  foreach ($result as $row) {
    $options[$row->id] = $row->status_readable;
  }

  $form['status'] = array(
    '#type' => 'radios',
    '#title' => t('What is the interview status?'),
    '#description' => t('Select the status of the interview.'),
    '#options' => $options,
    '#default_value' => $id,
    '#required' => TRUE,
  );

  $form['update'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );

  $form['#submit'][] = 'interview_tracker_update_form_submit';

  return $form;
}

function interview_tracker_update_form_submit($form, &$form_state) {

}

/**
 * Gets the list of interview statuses.
 *
 * @param int $id
 *   The interview id.
 *
 * @return array
 *   An array of row objects.
 */
function interview_tracker_get_interview($id = 0) {
  $query = db_select('interview_tracker', 'it');
  $query->leftJoin('interview_tracker_status', 'its', 'it.status=its.id');
  $query->fields('it');
  $query->fields('its');

  if (is_numeric($id) && $id > 0) {
    $result = $query->condition('id', $id, '=');
  }

  $result = $query->execute()->fetchAll();

  return $result;
}

/**
 * Gets the list of interview statuses.
 *
 * @return array
 *   An array of row objects.
 */
function interview_tracker_get_status() {
  $query = db_select('interview_tracker_status', 'its')
    ->fields('its')
    ->execute();

  $result = $query->fetchAll();
  return $result;
}
