<?php

/**
 * @file
 * Sometimes it can be hard to track all of the companies that you interview
 * for; the interview_tracker module can help save the day.
 *
 * @author Brian McVeigh
 */

/**
 * Implements hook_menu().
 */
function interview_tracker_menu() {
  $items['interview'] = array(
    'title' => 'Track',
    'description' => 'Track the status of companies you interviewed with.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('interview_tracker_page'),
    'access arguments' => array('view interview tracker'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function interview_tracker_permission() {
  return array(
    'view interview tracker' => array(
      'title' => t('View Interview Tracker'),
      'description' => t('View and edit the interview tracker.'),
    ),
  );
}

/**
 * This page contains a table of all the interviews.
 */
function interview_tracker_page($form, &$form_state) {
  // Write query and construct the table.
  $query = db_select('interview_tracker', 'it');
  $query->fields('it');
  $query->innerJoin('interview_tracker_status', 'its', 'it.id=its.id');

  // Execute the query.
  $result = $query->execute()->fetchAll();

  if (!empty($result)) {
    $rows = array();

    $header = array(
      t('Position Applied'),
      t('Company'),
      t('Comment'),
      t('Status'),
      t('Submitted Date'),
    );

    foreach ($result as $row) {
      $rows[] = array(
        $row->position,
        $row->company,
        $row->comment,
        $row->status_readable,
        date('F j, Y, g:i a', $row->submitted),
      );
    }

    $form['interview_table'] = array(
      '#type' => 'markup',
      '#markup' => theme('table', array('header' => $header, 'rows' => $rows)),
    );
  }

  $form['position_applied'] = array(
    '#type' => 'textfield',
    '#title' => t('Position applied for'),
    '#description' => t('Enter the position you applied for.'),
    '#required' => TRUE,
  );

  $form['company_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Company Name'),
    '#description' => t('Enter the name of the company you applied to.'),
    '#required' => TRUE,
  );

  $form['comment'] = array(
    '#type' => 'textarea',
    '#title' => t('Enter comments about interview.'),
    '#description' => t('Enter the comments you had about the interview.'),
    '#required' => FALSE,
  );

  $result = interview_tracker_get_status();

  $options = array();

  foreach ($result as $row) {
    $options[$row->id] = $row->status_readable;
  }

  $form['status'] = array(
    '#type' => 'radios',
    '#title' => t('What is the interview status?'),
    '#description' => t('Select the status of the interview.'),
    '#options' => $options,
    '#default_value' => 0,
    '#required' => TRUE,
  );

  $form['procesar'] = array(
    '#type' => 'submit',
    '#value' => t('Add interview!'),
  );

  return $form;
}

function interview_tracker_get_status() {
  $query = db_select('interview_tracker_status', 'its')
    ->fields('its')
    ->execute();

  $result = $query->fetchAll();
  return $result;
}
